### ISSUE TITLE
Cannot find module 'core-js/modules/es6.object.is'

### ISSUE THREAD

**Issue by charpeni** [DAB0mB/ReactNativeMeteorBoilerplate#13]
I tried to run this boilerplate following the instruction in the README.

```javascript
import 'meteor-client';
```

crash with this error: `Cannot find module 'core-js/modules/es6.object.is'`.

**Comment by ardatan** [comment]
It has to be fixed by https://github.com/DAB0mB/ReactNativeMeteorBoilerplate/commit/78ccb58c18efbc6ff1c14b8a4ec8f4fdd3464ad4
Please let me know if it still doesn't work.

**Comment by charpeni** [comment]
Fixed, thanks.
