### ISSUE TITLE
Error: Cannot find module '@babel/runtime/helpers/builtin/interopRequireDefault'

### ISSUE THREAD

**Issue by eugle** [DAB0mB/ReactNativeMeteorBoilerplate#15]
$ npm run api 
The error occurred and could not be continued

Error: Cannot find module '@babel/runtime/helpers/builtin/interopRequireDefault'

**Comment by ardatan** [comment]
https://forums.meteor.com/t/solved-cannot-find-module-babel-runtime-helpers-builtin-objectspread-after-update-meteor-to-1-6-1-1/43034

**Comment by diegolaciar** [comment]
meteor npm install @babel/runtime@7.0.0-beta.55

**Comment by CyberCyclone** [comment]
From the link above, this is the comment that fixed it for me:

> or simply remove the caret ^ in package.json and thus pin it to a specific version.
